# theme: jekyll-theme-cayman

# Site settings
title: Csy Blog
SEOTitle: Csy Blog
header-img: img/home-bg2.jpg
email: 6044407@qq.com
description: "前端开发, Web & Front-end Engineer"
keyword: "chenshuyao, csy, Csy Blog, 博客, 前端, Web, Css, Javascript, vue, react"
url: "https://chenshuyao.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico

# Analytics settings
# Baidu Tongji
ba_track_id: 'e86156d23996ffc318f764a3fdefa294'

# Google Analytics
ga_track_id: 'UA-134636983-1'
ga_domain: 'chenshuyao.cn'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Web Developer <br/> 盐于律己，甜以待人 "
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    IdeaEcho


# Build settings
highlighter: rouge
paginate: 10
plugins: [jekyll-paginate, jemoji]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e88c985c0284a1546702                            #生成的clientID
  clientSecret: d1cf8b8580eca871ae5eb03b23b799e163cfe080    #生成的clientSecret
  repo: IdeaEcho.github.io    #仓库名称
  owner: IdeaEcho    #github用户名
  admin: IdeaEcho
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [{
  title: "wumeilian's blog",
  href: "https://meilianwu.com/"
}]
